config/routes.rb
QL::Application.routes.draw do

  resources :admin

  resources :comment_votes

  resources :comments

  resources :votes
  resources :comments
  resources :posts do
    resource :comments
  end

  get 'posts' => 'posts#index'
  get 'users' => 'users#index'
      get 'sessions' => 'sessions#new'
  get 'admins' => 'admin#index'
  get 'comments'=> 'comments'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

   controller :posts do
    get 'votes'  => :voted
  end

  resources :users

  resources :sessions

  root :to => 'sessions#new'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

   validates :post_id, :presence => true
  validates :commenterID, :presence => true
  validates :body, :presence => true

  attr_accessible  :post_id, :body, :commenterID
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  skip_before_filter :authorizeAdmin, :only => [:new, :create, :show, :destroy]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    @comment.commentVotes = 0
    @comment.commenterID = session[:user_id]

    redirect_to post_path(@post)
    #respond_to do |format|
     @comment.save
      #  format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
       # format.json { render json: @comment, status: :created, location: @comment }
      #else
      #  format.html { render action: "new" }
      #  format.json { render json: @comment.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
   @post = Post.find(params[:postID])
    @comment = @post.comments.find(params[:commentID])
   if(@comment.commenterID.to_s == session[:user_id].to_s)

    @comment.destroy
   @post.save

    redirect_to @post
   else
     redirect_to @post, notice: 'You can not delete others comment'
   end

  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenterID %>
</p>
 
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>

<p>
  <b>Comment Votes:</b>
  <%= comment.commentVotes %>
</p>


<p>


    <%= link_to 'Destroy Comment', comment_path(:postID => @post.id,:commentID => comment.id),
              confirm: 'Are you sure?',:method => 'delete' %>

  <%= link_to 'Vote Comment', comment_votes_path(:postID => @post.id,:commentID => comment.id),
             :method => 'create'%>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Commenterid</th>
    <th>Body</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.commenterID %></td>
    <td><%= comment.body %></td>
    <td><%= comment.post %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Commenterid:</b>
  <%= @comment.commenterID %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>