config/routes.rb
QL::Application.routes.draw do

  resources :admin

  resources :comment_votes

  resources :comments

  resources :votes
  resources :comments
  resources :posts do
    resource :comments
  end

  get 'posts' => 'posts#index'
  get 'users' => 'users#index'
      get 'sessions' => 'sessions#new'
  get 'admins' => 'admin#index'
  get 'comments'=> 'comments'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

   controller :posts do
    get 'votes'  => :voted
  end

  resources :users

  resources :sessions

  root :to => 'sessions#new'

end

app/views/admin/_form.html.erb
<div class="depot_form">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %>
              prohibited this user from being saved:</h2>
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <fieldset>
        <legend>Enter User Details</legend>

        <div>
          <%= f.label :name %>:
          <%= f.text_field :name, :size => 40 %>
        </div>

        <div>
          <%= f.label :password, 'Password' %>:
          <%= f.password_field :password, :size => 40 %>
        </div>

        <div>
          <%= f.label :password_confirmation, 'Confirm' %>:
          <%= f.password_field :password_confirmation, :size => 40 %>
        </div>

        <div>
          <%= f.submit %>
        </div>

      </fieldset>
  <% end %>
</div>

app/views/admin/index.html.erb
<%= form_tag admins_path, :method => 'get' do %>

<%= link_to 'See Users Info', users_path%>
    <br>
<%= link_to 'See Posts Info', posts_path%>
     <br>
<%= link_to 'See Comments Info', comments_path%>
     <br>
<%= link_to 'See Post Vote Info', votes_path%>
     <br>
<%= link_to 'See Comment Vote Info', comment_votes_path%>
    <br>
    <%= link_to 'Create New Admin User', new_user_url%>


<% end %>
<%= link_to 'Log out', logout_url, :method => :delete  %>
<%= label 'Sing in as:','sign in as: '+session[:user_name] %>

app/views/admin/new.html.erb
<%= form_tag new_admin_url, :method => 'get' do %>
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
<% end %>