config/routes.rb
QL::Application.routes.draw do

  resources :admin

  resources :comment_votes

  resources :comments

  resources :votes
  resources :comments
  resources :posts do
    resource :comments
  end

  get 'posts' => 'posts#index'
  get 'users' => 'users#index'
      get 'sessions' => 'sessions#new'
  get 'admins' => 'admin#index'
  get 'comments'=> 'comments'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

   controller :posts do
    get 'votes'  => :voted
  end

  resources :users

  resources :sessions

  root :to => 'sessions#new'

end

app/models/post.rb
class Post < ActiveRecord::Base


  validates :title, :presence => true
  validates :content, :presence => true

  attr_accessible  :title, :content, :posterName

  has_many :comments, :dependent => :destroy


  def voted votesNum,postId


    sql=ActiveRecord::Base.connection()
    sql.update('UPDATE POSTS SET votes='+votesNum+' WHERE id='+postId)

  end

  def checkIfVoted postID,userID

    sql=ActiveRecord::Base.connection()
    result = sql.execute('SELECT * FROM VOTES WHERE postID='+postID+' AND userID='+userID)

    #Array results = Post.find_by_sql('SELECT * FROM VOTES WHERE postID='+postID+' AND postUserID='+userID)


  end

  def checkIfCommentVoted userID,postID,commentID

    sql=ActiveRecord::Base.connection()
    result = sql.execute('SELECT * FROM COMMENT_VOTES WHERE userID = '+userID+' AND postID='+postID+' AND commentID='+commentID)

    #Array results = Post.find_by_sql('SELECT * FROM VOTES WHERE postID='+postID+' AND postUserID='+userID)


  end

   def self.search(search, t)
    if search || t
      if t == "user"
        find(:all, :conditions => ['posterName = ?', search],:order=> 'weight DESC')
      else
        find(:all, :conditions => ['content LIKE ?', "%#{search}%"],:order=> 'weight DESC')
      end
    else
      find(:all)
    end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authorize, :only =>[:index,:show]
  skip_before_filter :authorizeAdmin
  # GET /posts
  # GET /posts.json


  def index
     @posts = Post.find(:all)
      @posts.each do |dec|
      dayDiff=Time.now.day - dec.created_at.day
      dec.weight = dec.votes-dayDiff
      dec.save
      end




    if params[:search] || params[:type]
      @posts = Post.search(params[:search], params[:type])
    else
      @posts = Post.all  :order => 'weight DESC'

    end






     respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
     end
     #end


      #@posts = Post.all :order => 'votes DESC'
     # @posts.each do |dec|
     # dayDiff=Time.now.day - dec.created_at.day
     # dec.weight = dec.votes-dayDiff
     # dec.save

    #end

  #end


    #@posts = Post.all :order => 'weight DESC'

    #respond_to do |format|
     # format.html # index.html.erb
     # format.json { render json: @posts }
    #end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit

    @post = Post.find(params[:id])
    if(@post.postUserID.to_s != session[:user_id].to_s)
      redirect_to @post, notice: 'You can not edit others post'
    else
      return
    #  @post = Post.find(params[:id])
    end
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(params[:post])
    @post.postUserID = session[:user_id]
    @post.votes = 0
    @post.weight = 100
    @post.posterName = session[:user_name]
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    if(@post.postUserID.to_s == session[:user_id].to_s || session[:user_aut].to_s=='1' )
      @post.destroy
      respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
      end
    else
      redirect_to @post, notice: 'You can not delete others post'


    end

  end





end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <!--<div class="field">
    <%= f.label :votes %><br />
    <%= f.number_field :votes %>
  </div>  -->
  <!--<div class="field">
    <%= f.label :postUserID %><br />
    <%= f.text_field :postUserID %>
  </div>        -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= form_tag posts_path, :method => 'get' do %>
    <p>
      <%= radio_button_tag :type, "user", params[:type] = 'user', :id => "user" %>User
      <%= radio_button_tag :type, "content", params[:type] = 'content', :id => "content" %>Content
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>

<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>PosterName</th>
    <th>Votes</th>
    <th>Weight</th>
    <th>Postuserid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= post.posterName%></td>
    <td><%= post.votes %></td>
    <td><%= post.weight %></td>
    <td><%= post.postUserID %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path%>
<%= link_to 'Admin See Infos here', admins_path%>
<%= link_to 'Log out',{ :controller =>"sessions",  :action => "destroy" },:method => :delete %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

<%= link_to 'Log out', logout_url, :method => :delete  %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>Votes:</b>
  <%= @post.votes %>
</p>

<p>
  <b>PosterName:</b>
  <%= @post.posterName %>
</p>



<h2>Comments</h2>
<%= render @post.comments %>



<h2>Add a comment:</h2>
<%= render "comments/form" %>




 <%= button_to "Vote for this Post", votes_path(:postID => @post.id)%>



<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<%= link_to 'Log out',{ :controller =>"sessions",  :action => "destroy" },:method => :delete %>